---
services:
  plantuml:
    build: ./plantuml
    image: ${CONTAINER_REGISTRY}${PLANTUML_IMAGE:-bin/plantuml}:${TAG:-latest}

  toilet:
    build: ./toilet
    image: ${CONTAINER_REGISTRY}${TOILET_IMAGE:-bin/toilet}:${TAG:-latest}

  dotnet:
    build:
      context: ./dotnet
      args:
        USERID: "${ARG_USER_ID:-1000}"
        USER_GROUPID: "${ARG_GROUP_ID:-1000}"
        DOTNET_SDK_VER: "${DOTNET_SDK_VER:-8.0}"
        VIM_DEPS: "${VIM_DEPS:-universal-ctags ripgrep yamllint nodejs}"
    image: ${CONTAINER_REGISTRY}${DOTNET_IMAGE:-dev/dotnet}:${DOTNET_SDK_VER:-8.0}

  puppeteer:
    build:
      context: ./puppeteer
      args:
        VIM_DEPS: "${VIM_DEPS:-universal-ctags ripgrep yamllint}"
    image: ${CONTAINER_REGISTRY}${PUPPETEER_IMAGE:-dev/puppeteer}:${TAG:-latest}

  jwt:
    build:
      context: ./jwt
    image: ${CONTAINER_REGISTRY}${JWT_IMAGE:-bin/jwt}:${TAG:-latest}
